server:
  #设置tomcat端口
  port: 8081
  servlet:
    #项目路径
    context-path: /springboot

debug: true

spring:
  datasource:
    # java JDBC驱动   mysql6版本及以上使用com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123

  # 解决无法直接访问templates下的html文件的解决办法
  resources:
    static-locations: classpath:/templates/,classpath:/static/

  redis:
    database: 0
    host: 118.25.195.112
    port: 6379
    password: 123

  devtools:
    restart:
      enabled: true  #设置开启热部署
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效

mybatis:
  #xml文件路径
  mapper-locations: classpath:mapper/*Mapper.xml
  #实体类路径(可以省略，在xml文件中有配置)
  type-aliases-package: com.zjq.springbootdemo.model
  #配置mybatis日志生成
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启mybatis的二级缓存
    cache-enabled: true
    # 设置一级缓存级别
    local-cache-scope: session

logging:
  config: classpath:log4j2.xml

shiro:
  sessionManager:
    #表示允许将sessionId放到cookie中
    sessionIdCookieEnabled: true
    #表示允许将sessionId放到url地址栏中
    sessionIdUrlRewritingEnabled: true
  #未获取授权时的默认跳转路径
  unauthorizedUrl: /unauthorized.html
  #表示开启shiro
  web:
    enabled: true
  #登陆成功后的跳转页面
  successUrl: /index.html
  #登陆界面
  loginUrl: /login.html

#添加属性，可注入bean
badguy:
  name: zjq

