server:
  #设置tomcat端口
  port: 8081
  servlet:
    #项目路径
    context-path: /springboot


spring:
  datasource:
    # java JDBC驱动   mysql6版本及以上使用com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123

mybatis:
  # xml文件路径
  mapper-locations: classpath:mapper/*Mapper.xml
  # 实体类路径(可以省略，在xml文件中有配置)
  # type-aliases-package: com.zjq.springbootdemo.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:log4j2.xml

#添加属性，可注入bean
badguy:
  name: zjq

